//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BehaviorDevelop.Properties {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BehaviorDevelop.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap ICON_SYMBOL_ATTRIBUTE {
			get {
				object obj = ResourceManager.GetObject("ICON_SYMBOL_ATTRIBUTE", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap ICON_SYMBOL_CLASS {
			get {
				object obj = ResourceManager.GetObject("ICON_SYMBOL_CLASS", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap ICON_SYMBOL_METHOD {
			get {
				object obj = ResourceManager.GetObject("ICON_SYMBOL_METHOD", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap ICON_SYMBOL_SCREEN {
			get {
				object obj = ResourceManager.GetObject("ICON_SYMBOL_SCREEN", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap ICON_SYMBOL_TAGGEDVALUE {
			get {
				object obj = ResourceManager.GetObject("ICON_SYMBOL_TAGGEDVALUE", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap ICON_SYMBOL_UIELEMENT {
			get {
				object obj = ResourceManager.GetObject("ICON_SYMBOL_UIELEMENT", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap NumberingOFF {
			get {
				object obj = ResourceManager.GetObject("NumberingOFF", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap NumberingON {
			get {
				object obj = ResourceManager.GetObject("NumberingON", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
